### ISSUE TITLE
Website Speed get very slow

### ISSUE THREAD

**Issue by chadhakavita** [UltraCart/rest_api_v2_sdk_php#11]
Hi,
I've noticed that my website speeds get slow when I use checkout API and we have but it has excellent internet speed. Could you please assist me regarding the same?

Regards,
kavita

**Comment by ucjonathan** [comment]
You’ve provided no details.   What API calls are you making?  Have you collected any timing data?  Are you asking for shipping estimates in your expansion?  Where is your server located?  What is the round trip latency from your connection to your server?

**Comment by chadhakavita** [comment]
Hi Jonathan,

I've mailed you. Please check it out.

Thanks
kavita
