### ISSUE TITLE
How do add/link multiple orders for single customer in ultracart using checkout API.

### ISSUE THREAD

**Issue by chadhakavita** [UltraCart/rest_api_v2_sdk_php#12]
Hi,

I have 3 upsell products and I would like to know how do I add them in the Ultracart backend using checkout API.
This is my main product: https://prnt.sc/j8yx5n

And after proceeding to buy this product, I have 3 more products which are coming 1 by 1 before checkout. Here is the screenshot of 1 of those upsell products: https://prnt.sc/j8yyz3

If customer proceeds to purchase the main product, he will get an option to add those upsell products one by one. And if the customer selects all/some of those upsell products. Those products will be added to cart along with the main product.

I would like to know how do I add/link those upsell products with the main product in ultracart?

**Comment by perrytew** [comment]
The easiest way to handle upsells is to allow UltraCart to do it.  Our upsell functionality is amazing.  
If you allow UltraCart to handle upsells, there is nothing more for you to do.  All you do is a normal checkout and when the cart information is collected, just do the handoff.  UltraCart handles the rest.

Are you doing a checkout handoff or is this a completely server side php checkout where you are ending the checkout by calling finalize?

=====================================
Instructions if you are managing the upsell yourself
=====================================
If you wish to do the upsells yourself, then when the customer has finished entering all their information:
1. call validate to ensure the cart is correct.
2. populate and set the upsell_after object

https://github.com/UltraCart/rest_api_v2_sdk_php/blob/master/docs/Model/CartUpsellAfter.md

You need to set either finalize_after_dts or finalize_after_minutes.  Either of those is required to ensure the cart is automatically converted to an order even if the customer closes the browser window early.  This will happen if you show too many upsells or annoying upsells.  They just leave.

After setting the upsell_after, do a cart update.  Once done, you may proceed to show your upsell pages.  If they click yes on an upsell, just load up the cart, add the item and update the cart.

If you do reach the end of your upsell gauntlet, call your finalizeOrder to complete the order in the same fashion as you would normally.

I would again like to stress that this is a crazy amount of work to do when UltraCart can do all of this for you.  Just set up your upsells, and call cart/checkoutHandoff.  UltraCart will then handle all the gory upsell logic and provide excellent upsell statistics and dashboard metrics.   But, some people enjoy pain.

**Comment by chadhakavita** [comment]
Hi Perry,

Yeah, I'm familiar with the Ultracart after upsell functionality but I'm doing the checkout on PHP server side. And I know it's a pain for me but I've to follow my client's instruction :)

Can I pass multiple item ID in the following line so that all the items get under the single order? If, yes then how can I add multiple item ID?
$item->setItemId('ITEM ID');

**Comment by perrytew** [comment]
We do not offer any shortcut method for adding multiple items.  You should add each item individually.
```php
$items = array();

$item1 = new \ultracart\v2\models\CartItem();
$item1->setItemId("BONE");
array_push($items, $item1);

$item2 = new \ultracart\v2\models\CartItem();
$item2->setItemId("SOME_ITEM");
array_push($items, $item2);

$item3 = new \ultracart\v2\models\CartItem();
$item3->setItemId("THIRD_ITEM_ID");
array_push($items, $item3);

$cart->setItems($items);
```

**Comment by chadhakavita** [comment]
Thanks Perry. This will work for me as well :smile:
