### ISSUE TITLE
Help create cart information then add payment, items  

### ISSUE THREAD

**Issue by HassanAbass** [UltraCart/rest_api_v2_sdk_php#15]
Hi. What I'm looking to do. A customer goes to [this page](http://menagebeauty.com/ ) and fills out the form on the right with Name, email, phone #, address. submit and then get sent to [order page](http://menagebeauty.com/order/): 
If they leave without completing the second page,I need to store the information they provided in first (shipping, billing info) without the order Item, payment info so I would like that info sent to Ultracart as a partial order.
in /order page they will add the payment and the selected package they want if they continue to second page
i used this [ref](https://ultracart.atlassian.net/wiki/spaces/ucdoc/pages/365658113/PHP+SDK+Sample+Add+externally+created+order) to make the order but then i get error saying :
error Please add at least one item to your shopping cart before checkout.
i dont want to add the order item immediately i just want to fill the info (shipping, billing)  then add the order item, payment to process the payment.
and i dont know how to add an item to cart ! is there any function that do that cart->setOrderItem()

**Comment by perrytew** [comment]
My apologies for never responding.  I'm closing this ticket since it's been years.  Please re-open if we can assist in any manner.
