### ISSUE TITLE
Can't able to process order error  return on store_cvv...

### ISSUE THREAD

**Issue by koumotodragon** [UltraCart/rest_api_v2_sdk_php#17]
Hi Team,

I have configured Ultracart with new website. However, its not processing
orders and its asking for cvv2 number and breaks the operations.
Its working on our other website with the same merchant. 
Here is the snippet of the code. Kindly check and let us know if there is
any issues. Also you can see the resulting error we are getting.

```php
  // --- Payment Block ---
 $creditCardNumber = $_SESSION['cc_no'];
 $cvv = $_SESSION['cvv_no'];
 $_SESSION['coupon'] = $_POST['couponw3c'];
 $_SESSION['shipping_mehtod'] = $_POST['shipping_method_choose'];

 $_SESSION['hidden_shipping_charges'] = $_POST['shipping_price_val'];
 $_SESSION['hidden_total_charges'] = $_POST['tot'];
 $_SESSION['hidden_subtotal_charges'] = $_POST['subtot'];
 $payment = new \ultracart\v2\models\CartPayment();
 $creditCard = new \ultracart\v2\models\CartPaymentCreditCard();
 $store_cc_result = $hosted_fields->store_number($creditCardNumber);
 if ($store_cc_result->success) {
   // the server will tie the actual card number to the cart later, but the mask must be added
   $creditCard->setCardNumber($store_cc_result->maskedValue);
   $creditCard->setCardExpirationMonth($_SESSION['cc_exp_month']);
   $creditCard->setCardExpirationYear($_SESSION['cc_exp_yr']);
   $creditCard->setCardType($store_cc_result->cardType);
 }
 $store_cvv_result = $hosted_fields->store_cvv($cvv);
 if ($store_cvv_result->success) {
   // the server will tie the actual cvv to the cart later, but the mask must be added
   $creditCard->setCardVerificationNumber($store_cvv_result->maskedValue);
 }
 $payment->setPaymentMethod("Credit Card");
 $payment->setCreditCard($creditCard);
 $cart->setPayment($payment);
 // --- End Payment Block ---
```
-----------------------------------------------
At the time debugging, I am getting following result.

stdClass Object ( [success] => [errorMessage] => Invalid CVV2 number
provided for storage. )

Hence, can your developer guys check whats wrong in this?

**Comment by perrytew** [comment]
Mr. Dragon,
Would you please check your hosted fields php file and make sure none of the urls are using secure.ultracart.com?   They should all be using token.ultracart.com.   I did find some old scripts still using the secure, and those will no longer work.   

Please let me know what you find.

Regards,
Perry

**Comment by koumotodragon** [comment]
Its not using secure.ultracart.com.

**Comment by koumotodragon** [comment]
it suddenly started working today and then after few hours got the same problem. CVV2 missing even after I entered it.

**Comment by perrytew** [comment]
Within the HostedFields.class.php, add this line to block of curl_setopt calls:

```php
curl_setopt($ch, CURLOPT_HTTPHEADER, array('Expect:'));
```

You should add that in two places, _around_ line 28 and 99.  It doesn't matter the order of curl_setopt calls, so you may just add it as the first one, like this:

```php
        $ch = curl_init($url);
        curl_setopt($ch, CURLOPT_HTTPHEADER, array('Expect:')); // <-- this is the new line
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
        curl_setopt($ch, CURLOPT_HTTPHEADER, array('Referer: https://token.ultracart.com/'));
```


Also, add some logging.  Find every occurrence this:
``` $result = curl_exec($ch); ```

and change it to this:
```php
$result = curl_exec($ch);
error_log($result);
``` 

That should provide some insight.  Let's see how

**Comment by koumotodragon** [comment]
Here is the response I am getting. 
[13-Sep-2018 15:53:50 UTC] {"success":true,"maskedValue":"XXXX-XXXX-XXXX-1111","cardType":"VISA"}
[13-Sep-2018 15:53:50 UTC] {"success":false,"errorMessage":"Invalid CVV2 number provided for storage."}
[13-Sep-2018 15:54:44 UTC] {"success":true,"maskedValue":"XXXX-XXXX-XXXX-1111","cardType":"VISA"}
[13-Sep-2018 15:54:44 UTC] {"success":false,"errorMessage":"Invalid CVV2 number provided for storage."}
Below is the cvv I passed and second is the error I am getting. 
[13-Sep-2018 15:57:20 UTC] 890
[13-Sep-2018 15:57:20 UTC] {"success":false,"errorMessage":"Invalid CVV2 number provided for storage."}

**Comment by koumotodragon** [comment]
Hi Perry, Did you get anything replicated at your end ? I also sent a test case details where you can try to replicate the issue. Thanks

**Comment by perrytew** [comment]
No, I could not replicate.   I can't find this case though.   Do you have a case no.?  It doesn't appear in my queue, so I suspect it was routed incorrectly.  Please also email support@ultracart.com and send me your entire HostedFields.class.php and the block of code you use to call it and return the value.    It's very strange that the CC number stores and the CVV number does not.    Perhaps a data type issue?    While I wait on your code, I"m going to try something else with my own harness.

**Comment by perrytew** [comment]
Hold off on sending any more data.   I'll be in touch.

**Comment by perrytew** [comment]
Please try your test again.  I had an engineer do a review, and they found that there was a difference between the CC and CVV in terms of timestamp allowances.   Those have been made identical and my test harness is working now.    This is a corner case related to php, and very few people use the HostedFields.class.php (it puts your server within PCI scope -- dangerous), so I apologize for the delays fixing it.   Please let me know if you continue experiencing problems.

**Comment by koumotodragon** [comment]
Thanks, I did the test and I am getting now this error. Please check. 
" Please add at least one item to your shopping cart before checkout."

**Comment by perrytew** [comment]
Can't say without seeing some code.   Please show me your item code snippet.  What merchant ID are you using and what item ID are you adding?

**Comment by koumotodragon** [comment]
Merchant id: NF201. 
Item Id: 5BTL-NF
Attached are the code files.
[create-order.txt](https://github.com/UltraCart/rest_api_v2_sdk_php/files/2406678/create-order.txt)
[HostedFields.class.txt](https://github.com/UltraCart/rest_api_v2_sdk_php/files/2406679/HostedFields.class.txt)

**Comment by perrytew** [comment]
I received your files and downloaded them.  I'll review them.   I had to delete your post because you included your API key within your code.   Thanks.

**Comment by koumotodragon** [comment]
ok thanks. Please let me know if you find anything on this.

**Comment by perrytew** [comment]
I reviewed your code.  I didn't see anything structurally wrong with it.  What item ids are you using?
I still don't know what merchant id and item ids you're using.
     
When you perform an updateCart call, are you examining the cart object at that time?  Review the items array and ensure the item is in your cart.  If not, make sure the item doesn't have a restriction or is inactive.

Also, got ahead and set the item quantity to 1 just to be sure.

**Comment by koumotodragon** [comment]
Merchant id: NF201
Item id: 1BTL-REBILL or 1BTL-ILP
Yes I am checking like that. So the problem is, it works in 80% cases and gives error in 20% cases with same values and same item selections.

**Comment by perrytew** [comment]
I need some more information.  What is different when it fails versus succeeds?  Do you have different paths to the checkout?  Are the customers entering the checkout page, leaving, then returning?   Can you point me to the cart ids (so I can review the API logs) of a success and a fail?
