### ISSUE TITLE
Where are the custom fields located in the API?

### ISSUE THREAD

**Issue by darkstorm2** [UltraCart/rest_api_v2_sdk_php#19]
Hi Perry,

I'm looking specifically for these 4 fields:

Custom Field 1	
Custom Field 2
Mailing List
Country

I found country code, but not the country name (maybe not in there, which is fine).

I couldn't find a custom field object to reference so I'm stuck there.  Otherwise, I've found the other 23 fields from their objects/arrays and it seems to be working fine.

Thanks again for your help!

-Bryant

**Comment by ucjonathan** [comment]
@darkstorm2 We provide the standard ISO-3166 country code.  There are tables of the expanded values readily available on the internet if you want to display it fully.  It's just more consistent from a system integration perspective to work with the codes.

order -> checkout will contain the custom fields.

order -> marketing -> mailing_list_opt_in is the other field.

**Comment by perrytew** [comment]
Hey Bryant.  Re-open this if you need more fields mapped.
