### ISSUE TITLE
Documentation for "$_expland"

### ISSUE THREAD

**Issue by milanstosic** [UltraCart/rest_api_v2_sdk_php#20]
I saw the following on a few places in code examples:

`$_expand = "_expand_example"; // string | The object expansion to perform on the result.  See documentation for examples`

Can you tell me where to find documentation for examples because I wasn't able to find it (searched through your website, goggled, etc. but couldn't find it) and there's no link in the documentation.

P.S. Maybe is's something obvious but I wasn't aware of it.

**Comment by ucjonathan** [comment]
@milanstosic The documentation for the expansion is available here:

https://www.ultracart.com/api/

For example the expansion on the order resource  is:

![image](https://user-images.githubusercontent.com/5116030/123129088-ac9a5b00-d419-11eb-8024-c19bc91a17f3.png)

**Comment by milanstosic** [comment]
Ok, thank you. 

Can you, please, give me the link of the page from the screenshoot, because I can't find that part on https://www.ultracart.com/api/ ? I went through all the items/pages in the upper right dropdown and I couldn't find it.

**Comment by ucjonathan** [comment]
Underneath each resource type in the navigation menu is an entry for the Expansion.  

![image](https://user-images.githubusercontent.com/5116030/123319505-7c78b800-d4fe-11eb-9d21-f68cde45d98d.png)

**Comment by milanstosic** [comment]
Hi,

Thank you! I'm using smaller screen and I don't see sidebar like on your screenshoot, but I have a dropdown in the upper right corner with the same list.

Anyway, your answer helped me find what I needed.

Thank you!
