### ISSUE TITLE
Updating an Auto order

### ISSUE THREAD

**Issue by him-developer** [UltraCart/rest_api_v2_sdk_php#3]
Hello Perry,

I have been trying to update an Auto order using this new API from last couple of days but haven't got much success. Below is the code and error we are receiving:

        $data["_expand"] = 'original_order,original_order.shipping'; 
        $uri = PATH.'/auto_order/auto_orders/'.$auto_order_oid.'?'.http_build_query($data);
        
        $result = \Httpful\Request::get($uri)                  // Build a GET request...
        ->addHeader('X-UltraCart-Api-Version', API_VER) 
        ->addHeader('x-ultracart-simple-key',SIMPLE_KEY)
        ->addHeader('cache-control', 'no-cache') 
        ->send();   
        
        $auto_order = $result->body->auto_order;
        $auto_order->original_order->shipping->first_name="New FirstName";
        
        $uri = PATH.'/auto_order/auto_orders/'.$auto_order_oid;
        
        $update_result = \Httpful\Request::put($uri)                  // Build a PUT request...
        ->sendsJson()
        ->body(json_encode($auto_order))
        ->addHeader('X-UltraCart-Api-Version', API_VER) 
        ->addHeader('x-ultracart-simple-key',SIMPLE_KEY)
        ->addHeader('cache-control', 'no-cache') 
        ->send();
Errors:
[developer_message] => Server side error.  Please try your request again.  If it continues to fail, contact UltraCart Support.
[user_message] => Server side error.  Please try your request again.  If it continues to fail, contact UltraCart Support.
                
Can you provide some examples to update quantity, frequency and next shipment date of an AutoOrder?

Thanks 
Himanshu Saini.

PS: Is there any other better way to reach you? We have been planning to use this new API extensively and I don't want to create a new issue here for every hurdle we face.

**Comment by perrytew** [comment]
Himanshu,
We're seeing the error in our server logs related to your calls.   We have a null pointer exception on our site.  At first glance, it looks like an assumption was made out some merchant settings.   Please give us a few hours to analyze  and correct our problem.

**Comment by him-developer** [comment]
Hello Perry, 

I am able to update Billing and shipping addresses now.

Can you provide some examples to update quantity, frequency and next shipment date of an AutoOrder?
As while trying below code to update Arbitrary quantity of an item and getting "Invalid item.length specified." error.
Length value is originally not part of this item.

        $auto_order->original_order->items[0]->arbitrary_quantity = 2 ;
        $uri = PATH.'/auto_order/auto_orders/'.$auto_order_oid;
        
        $update_result = \Httpful\Request::put($uri)                  // Build a PUT request...
        ->sendsJson()
        ->body(json_encode($auto_order))
        ->addHeader('X-UltraCart-Api-Version', API_VER) 
        ->addHeader('x-ultracart-simple-key',SIMPLE_KEY)
        ->addHeader('cache-control', 'no-cache') 
        ->send();

**Comment by perrytew** [comment]
Hello Him,
Sorry about the delay.  I'll try to have you an example tomorrow, and have this bug fixed.

**Comment by perrytew** [comment]
Him, found a bug in the update for auto order items with regard to the primary key.  We'll have it fixed in production on 7/3.  Apologies for the delay.

**Comment by perrytew** [comment]
Code is in production.  You should be able to update without issue now.  
Here's the code with our SDK:
```php
require_once(__DIR__ . '/SwaggerClient-php/autoload.php');
$simple_key = '4256aaf6dfedfa01582fe9a961ab0100216d737b874a4801582fe9a961ab0100';
ultracart\v2\Configuration::getDefaultConfiguration()->setApiKey('x-ultracart-simple-key', $simple_key);
ultracart\v2\Configuration::getDefaultConfiguration()->addDefaultHeader("X-UltraCart-Api-Version", "2017-03-01");

$auto_order_oid = 2078718;  // this is found either by looping through auto orders, or from the back end.

$auto_order_api = new ultracart\v2\Api\AutoorderApi();

$auto_order_response = $auto_order_api->autoOrderAutoOrdersAutoOrderOidGet($auto_order_oid, "items");
$auto_order = $auto_order_response->getAutoOrder();

$auto_order->getItems()[0]->setArbitraryQuantity(4);

$auto_order_response = $auto_order_api->autoOrderAutoOrdersAutoOrderOidPut($auto_order, $auto_order_oid);
```

If you're still receiving an error?  Please give me a complete script that I can run and I'll look at it.  It would also help if you can provide the JSON payload that you're submitting.
