### ISSUE TITLE
`401 Unauthorized` response Error

### ISSUE THREAD

**Issue by chadhakavita** [UltraCart/rest_api_v2_sdk_php#7]
I am getting following error.Please have a look and revert me ASAP:

Fatal error: Uncaught ultracart\v2\ApiException: [401] Client error: GET https://secure.ultracart.com/rest/v2/checkout/cart?_expand=checkout%2Citems resulted in a 401 Unauthorized response: {"error":{"developer_message":"Permission Denied.","user_message":"Permission Denied."},"metadata":{}} in /home/dsdevelo/public_html/demo/CRM/vendor/UltraCart/rest_api_v2_sdk_php/lib/api/CheckoutApi.php:728 Stack trace: #0 /home/dsdevelo/public_html/demo/CRM/vendor/UltraCart/rest_api_v2_sdk_php/lib/api/CheckoutApi.php(703): ultracart\v2\api\CheckoutApi->getCartWithHttpInfo('checkout,items') #1 /home/dsdevelo/public_html/demo/CRM/sync.php(52): ultracart\v2\api\CheckoutApi->getCart('checkout,items') #2 {main} thrown in /home/dsdevelo/public_html/demo/CRM/vendor/UltraCart/rest_api_v2_sdk_php/lib/api/CheckoutApi.php on line 728

Following is my code:

<?php
set_time_limit(3000);
ini_set('max_execution_time', 3000);
ini_set('display_errors', 1);
?>
<!DOCTYPE html>
<html>
<body>
<?php
/**
 * Created by PhpStorm.
 * User: perry
 * Date: 4/25/2017
 * Time: 5:09 PM
 */

error_reporting(E_ALL);

// BEWARE: Almost every item here starts with 'Cart'.  There are similar items
// with other APIs.  Do not mistakenly use the other items.
// For example:  CartItem vs. Item, CartItemOption vs. ItemOption.  CartPaymentCreditCard vs. CustomerCard.

// initialization code
require_once './vendor/autoload.php';
// See https://github.com/UltraCart/hosted_fields for this file.
require_once('./hosted_fields/HostedFields.class.php');

// Configure API key authorization: ultraCartSimpleApiKey
$api_key = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
ultracart\v2\Configuration::getDefaultConfiguration()->setApiKey('x-ultracart-simple-key', $api_key);

$client = new GuzzleHttp\Client(['verify' => true, 'debug' => false]);
$config = ultracart\v2\Configuration::getDefaultConfiguration();
$headerSelector = new \ultracart\v2\HeaderSelector();

//$auto_order_api = new ultracart\v2\api\AutoOrderApi($client, $config, $headerSelector);

$checkout_api = new ultracart\v2\api\CheckoutApi();
echo "<pre>";   print_r($checkout_api); echo "</pre>";  die('Error Detect!');
// expansion should contain all the objects that will be needed throughout the checkout.
// see https://www.ultracart.com/api/#Topic3 for the complete list.
// This expansion list should be supplied for each get/put throughout or data may be lost on the return objects.
//$expansion = "billing,checkout,coupons,items,payment,settings.shipping.estimates,shipping,summary,taxes,coupons";

$expansion = "checkout,items";
// The expansion above doesn't include much of the item objects because they're not needed.  For example, we don't
// need the item multimedia because we're not showing this cart to an end customer like a javascript implementation would

$get_response = $checkout_api->getCart($expansion);

if($get_response->getErrors() != null &&  count($get_response->getErrors()) > 0){
    // handle errors here.
    die('System error.  Could not retrieve shopping cart.');
} else {
    $cart = $get_response->getCart();
}

**Comment by ucjonathan** [comment]
I've cleared out the API key that you posted after I warned you to XXXXXX out the content. Have you verified that you have an a correct API key and that the API key has been granted permissions to the checkout REST API.

**Comment by chadhakavita** [comment]
Yeah, I have verified that I have correct API key and also give permission to check out REST API. Please have a look on screenshot:
https://prnt.sc/iyc8sw

**Comment by chadhakavita** [comment]
Hi Jonathan,
I'm waiting for your response.

**Comment by perrytew** [comment]
chadhakavita,
Please email me your entire script if possible.  
Email it to support@ultracart.com and put "Attention Perry" in the subject.

I'd like to review it.
Thank you.

**Comment by perrytew** [comment]
Please post here when you've emailed it so I'll get a notification and know to go check the support queue.
Thanks.

**Comment by chadhakavita** [comment]
Hi Perry,
I have emailed you regarding my issue. Could you please have a look?

Thanks,
kavita

**Comment by perrytew** [comment]
What is the merchant id you're working with, Kavita?

**Comment by perrytew** [comment]
Kavita,

Change this line:
```php
$checkout_api = new ultracart\v2\api\CheckoutApi();
```

```php
$checkout_api = new ultracart\v2\api\CheckoutApi($client, $config, $headerSelector);
```

The default constructor for CheckoutApi will not have proper configuration.

Regards,
Perry

**Comment by perrytew** [comment]
I see my name in the code sample you originally posted, so you must've started with one of my sample that I fear is out of date.  Do you recall where you got it from?   It will probably need updating.

**Comment by chadhakavita** [comment]
Hey Perry,
Great job...It's working now and I have taken the code from https://www.ultracart.com/api/#resource_checkout.html (PHP) sample.

Really Appreciated :)

**Comment by perrytew** [comment]
I've updated the docs.  Our apologies for the outdated code sample.
