### ISSUE TITLE
How to add order in ultracard CRM using web API

### ISSUE THREAD

**Issue by chadhakavita** [UltraCart/rest_api_v2_sdk_php#8]
Hi Perry,

Could you please guide me how I can insert orders in ultracart CRM using API? As I'm not getting the things in the doc. I just want to add order details and don't want credit card functionality in CRM using API.If you have any live example then please share with me that would be a great help for me to understand.

Regards,
kavita

**Comment by perrytew** [comment]
Kavita,
We have an Order API, but that is only for managing existing orders within the system.  Any new orders must be entered via the Checkout API.   Let me see what examples we have of creating an order in the system.

**Comment by chadhakavita** [comment]
Perry,
Actually, my concern is that I want to get the order details from the different website and need to insert the order details in ultracart CRM. Is that possible?

**Comment by perrytew** [comment]
If the financial transaction is happening externally, then you should import the order as a payment type of "Purchase Order".  Put the Purchase Order Number as the external system's order id.  I'll work up an example for you.

**Comment by perrytew** [comment]
Here's some sample code.

https://ultracart.atlassian.net/wiki/spaces/ucdoc/pages/365658113/PHP+SDK+Sample+Add+externally+created+order

**Comment by chadhakavita** [comment]
Hey Perry, I don't want payment method and shipping method as they are being managed by the different website. Will the above-mentioned example is relevant?

**Comment by perrytew** [comment]
You must have some kind of payment method.  One is required.   The Purchase Order was suggested because it allows for a way to tie the UltraCart order to your external system via the Purchase Order Number.   However, if you wish to forego a payment method, we suggest a payment method of 'Cash'.   Some of our customers with "bricks and clicks" use 'Cash' when they're entering an order they handled inside their physical location.

Shipping method is not required if the total weight of the items is zero.  Any **non-zero** weight will require shipping and therefore a shipping method.    If you have non-zero weight items, then you can always create a dummy shipping method and use that method.

**Comment by chadhakavita** [comment]
No, I mean shipping method and payment method is handled by another website. I just need to take the order details, Shipping Address from that website and insert the order in the CRM.

**Comment by perrytew** [comment]
Yes, I understand.  And you'll need to provide some kind of Payment Method, such as "Cash" to fake the field.  As for shipping method, you'll have to provide something if the weight of any item is non-zero.  Fake or real.

**Comment by chadhakavita** [comment]
Okay. let me go through the example that you mentioned above.

**Comment by perrytew** [comment]
Once you put together a sample, let me know and give me the relevant shipping and payment sections if you encounter any errors.  I'll help.

**Comment by chadhakavita** [comment]
Sure Perry.

**Comment by chadhakavita** [comment]
Hey Perry,
What if I don't use order ID in code?
$purchaseOrderNumber = "1234567890"; // this should be the order id from the external system.

OR if this is mandatory can I generate the random number in this code. Will that clash somewhere?

**Comment by perrytew** [comment]
No, it does not have to be unique.  It's just something to tie two systems together.  If you don't need to tie the systems together, just use Cash.   You'll avoid adding meaningless data to the system.

**Comment by chadhakavita** [comment]
Okay. I've one more question.When I transfer all the composer files and API file for inserting order in CRM I'm getting 500 Error. Could you please tell me why this is happening?

**Comment by chadhakavita** [comment]
Hey Perry, I came to know that the 500 Error is because of PHP version on the server. Is there any way to work with lower than 5.5 PHP version?

**Comment by perrytew** [comment]
Kavita,

My apologies, but we cannot.  Our libraries are generated by swagger and we are locked into what they support.

https://swagger.io/swagger-codegen/
https://github.com/swagger-api/swagger-codegen

Regards,
Perry

**Comment by chadhakavita** [comment]
Hey Perry, I have upgraded the PHP version to 5.5.38 on my server but this time I'm getting Fatal error: Interface 'Psr\Http\Message\RequestInterface' not found in /XXX/public_html/vendor/guzzlehttp/psr7/src/Request.php

I've installed the composer on other server and copied the composer's files from that server and pasted to the new server. Is there any probability that Fatal Error is because I've pasted the composer files from another server instead of installing?

**Comment by perrytew** [comment]
Kavita,
You should consider starting new github issues for each new issue.  It helps those who come after you when they're searching for the same problem.   At UltraCart, we're not PHP experts, so I don't know how to advise you on this issue.

I did find others who have the same problem:
https://stackoverflow.com/questions/39033244/psr-http-message-requestinterface-not-found
https://github.com/guzzle/guzzle/issues/1947

But there wasn't a clear solution on the issue.

This post here:
https://www.extly.com/forum/16-problem-and-bug-reports/6793-extly-extensions-fatal-error-after-upgrading-autotweet-component.html

seems to indicate that it's an issue of missing files on the server.  I'm not sure how to advise you beyond that.  Perhaps uninstalling and reinstalling some of the packages?   Not being a PHP shop and not experiencing this issue first hand, that's the best I know to advise.

**Comment by chadhakavita** [comment]
Thanks, Perry I'll look into this. Thanks for your support. You are awesome :)
